# Build stage
FROM golang:1.23-alpine AS builder

WORKDIR /app

# Copy go mod and sum files
COPY go.mod go.sum ./

# Download all dependencies
RUN go mod download

# Copy the source code
COPY . .

# Build the application
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o transaction_processor ./cmd/transaction_processor

# Final stage
FROM alpine:3.18

WORKDIR /app

# Copy the binary from builder
COPY --from=builder /app/transaction_processor .

# Copy configs directly to the expected location
COPY configs/transaction_processor.env /app/configs/

# Copu migrations
COPY migrations /app/migrations

# Command to run
CMD ["./transaction_processor"]